### ISSUE TITLE
plugin does not work with a tool different than github

### ISSUE THREAD

**Issue by danibaeyens** [vtex/danger-plugin-keepachangelog#9]
Plugin crashes when trying to fetch the PR metadata as it's considering GitHub as the only possible backend.
IMHO, the easier fix would be to make that check on the dangerfile (and not trigger keepachangelog) or use an option to define if it's trivial or not to (for instance) trigger a warn or an error.

It's easy to implement on any way. I'm open to discuss but I'd prefer a tool-agnostic implementation
(Or alternatively, extend to include all tools, which is difficult to test)
What do you think?

**Comment by selabie68** [comment]
+1 On this

Trying to run on Gitlab.com yields the following error as gitlab data is under `danger.gitlab`

```node
Error:  TypeError: Cannot read properties of  (reading 'pr')
    at <project_root>/node_modules/danger-plugin-keepachangelog/dist/index.js:24:34
    at Generator.next (<anonymous>)
    at <project_root>/node_modules/danger-plugin-keepachangelog/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (<project_root>/node_modules/danger-plugin-keepachangelog/dist/index.js:4:12)
    at keepachangelog (<project_root>/node_modules/danger-plugin-keepachangelog/dist/index.js:22:12)
    at Object.<anonymous> (dangerfile.ts:5:51)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at requireFromString (<project_root>/node_modules/require-from-string/index.js:28:4)
    at <project_root>/node_modules/danger/distribution/runner/runners/inline.js:161:68
```
